#!/usr/bin/env Rscript

library(jsonify)
library(cowplot)
library(dplyr)
library(gapminder)
library(ggplot2)
library(ggpmisc)
library(ggpubr)
library(ghibli)
library(magrittr)
library(plotly)
library(ROBIFastread)
library(seqinr)
library(taxize)
library(taxonomizr)
library(tidyverse)
library(treemapify)
library(vegan)
